(module
 (import "wasi_snapshot_preview1" "fd_write" (func $__wasi_fd_write (param i32 i32 i32 i32) (result i32)))
 (import "env" "__host_argc" (func $__host_argc (result i64)))
 (import "env" "__host_argv" (func $__host_argv (param $index i64) (param $buf_ptr i32) (param $buf_len i32) (result i32)))
 (import "env" "__host_stdin_read" (func $__host_stdin_read (param $buf_ptr i32) (param $buf_len i32) (result i32)))
(import "env" "__sarif_env_get" (func $__sarif_env_get (param i32) (result i32)))
(import "env" "__sarif_env_set" (func $__sarif_env_set (param i32 i32) (result i32)))
(import "env" "__sarif_env_remove" (func $__sarif_env_remove (param i32) (result i32)))
(import "env" "__sarif_env_keys" (func $__sarif_env_keys (result i32)))
(import "env" "__sarif_dir_create" (func $__sarif_dir_create (param i32) (result i32)))
(import "env" "__sarif_dir_remove" (func $__sarif_dir_remove (param i32) (result i32)))
(import "env" "__sarif_dir_list" (func $__sarif_dir_list (param i32) (result i32)))
(import "env" "__sarif_dir_exists" (func $__sarif_dir_exists (param i32) (result i32)))
(import "env" "__sarif_dir_current" (func $__sarif_dir_current (result i32)))
(import "env" "__sarif_dir_change" (func $__sarif_dir_change (param i32) (result i32)))
(import "wasi_snapshot_preview1" "proc_exit" (func $proc_exit (param i32)))
(import "env" "__sarif_process_id" (func $__sarif_process_id (result i32)))
(import "wasi_snapshot_preview1" "clock_time_get" (func $__wasi_clock_time_get (param i32 i64 i32) (result i32)))
(import "env" "__sarif_clock_sleep" (func $__sarif_clock_sleep (param i32)))