[package]
name = "sarif_orchestrator"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true

[features]
default = ["backend-wasm"]
backend-wasm = ["sarif_codegen/backend-wasm", "wasmtime"]
backend-native = ["sarif_codegen/backend-native"]

[dependencies]
sarif_codegen = { path = "../sarif_codegen" }
sarif_frontend = { path = "../sarif_frontend" }
sarif_syntax = { path = "../sarif_syntax" }
wasmtime = { workspace = true, optional = true }

[dev-dependencies]
wat = { workspace = true }

[lints]
workspace = true
